#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Sun Apr 19 23:04:21 CEST 2020
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
echo "xvlog --incr --relax -prj unknown_vlog.prj"
ExecStep xvlog --incr --relax -prj unknown_vlog.prj 2>&1 | tee compile.log

echo "xvhdl --incr --relax -prj unknown_vhdl.prj"
ExecStep xvhdl --incr --relax -prj unknown_vhdl.prj 2>&1 | tee -a compile.log

