# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: mapping.xdc

# XDC: timing.xdc

# IP: ip/tri_mode_ethernet_mac_0_2/tri_mode_ethernet_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_mode_ethernet_mac_0 || ORIG_REF_NAME==tri_mode_ethernet_mac_0} -quiet] -quiet
