# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config  -id {Project 1-467}  -string {{CRITICAL WARNING: [Project 1-467] UCF constraints are not supported in Vivado (gcu_v2_fw_v0.ucf). Please convert these constraints to XDC and add then add the converted XDC constraints file to the project.}}  -suppress 
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.cache/wt [current_project]
set_property parent.project_path /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/udp_build_arp.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/ipbus_trans_decl.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/ipbus_ctrl.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/transactor_cfg.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/udp_do_rx_reset.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/transactor.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/stretcher.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/udp_build_payload.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/udp_if_flat.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/udp_ipaddr_block.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/udp_buffer_selector.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/udp_dualportram_tx.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/ipbus_package.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/udp_rxram_mux.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/trans_arb.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/udp_dualportram.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/udp_tx_mux.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/transactor_sm.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/udp_build_ping.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/udp_status_buffer.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/udp_rxtransactor_if_simple.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/udp_byte_sum.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/udp_dualportram_rx.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/udp_build_status.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/udp_rxram_shim.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/udp_build_resend.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/ipbus_addr_decode.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/udp_rarp_block.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/udp_txtransactor_if_simple.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/udp_clock_crossing_if.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/transactor_if.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/ipbus_fabric.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/udp_packet_parser.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/dpram/ipbus_dpram.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/top/top_level.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/imports/imports/tri_mode_ethernet_mac_0_fifo_block.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/system_clocks.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/imports/imports/tri_mode_ethernet_mac_0_ten_100_1g_eth_fifo.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/imports/imports/tri_mode_ethernet_mac_0_support.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/imports/imports/tri_mode_ethernet_mac_0_reset_sync.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/imports/imports/tri_mode_ethernet_mac_0_tx_client_fifo.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/imports/imports/tri_mode_ethernet_mac_0_rx_client_fifo.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ipbus/clock_div.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/imports/imports/tri_mode_ethernet_mac_0_bram_tdp.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/imports/imports/tri_mode_ethernet_mac_0_sync_block.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/new/fir.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/new/master_fir.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/spi_master/spi_master.vhd
  /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/spi_master/spi_master_flash.vhd
}
read_ip -quiet /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ip/tri_mode_ethernet_mac_0_2/tri_mode_ethernet_mac_0.xci
set_property used_in_implementation false [get_files -all /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ip/tri_mode_ethernet_mac_0_2/synth/tri_mode_ethernet_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ip/tri_mode_ethernet_mac_0_2/synth/tri_mode_ethernet_mac_0.xdc]
set_property used_in_implementation false [get_files -all /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ip/tri_mode_ethernet_mac_0_2/synth/tri_mode_ethernet_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ip/tri_mode_ethernet_mac_0_2/synth/tri_mode_ethernet_mac_0_clocks.xdc]

read_ip -quiet /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ip/vio_dpram/vio_dpram.xci
set_property used_in_implementation false [get_files -all /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ip/vio_dpram/vio_dpram.xdc]
set_property used_in_implementation false [get_files -all /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/sources_1/ip/vio_dpram/vio_dpram_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/constrs_1/mapping.xdc
set_property used_in_implementation false [get_files /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/constrs_1/mapping.xdc]

read_xdc /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/constrs_1/timing.xdc
set_property used_in_implementation false [get_files /home/student08/Desktop/progetto_finale/exercise_2/final_project_immacolato/Progetto/firmware/final_ex.srcs/constrs_1/timing.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_level -part xc7a35tcsg324-1 -flatten_hierarchy none


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_level.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
