-- Address decode logic for ipbus fabric
--
-- This file has been AUTOGENERATED from the address table - do not hand edit
--
-- We assume the synthesis tool is clever enough to recognise exclusive conditions
-- in the if statement.
--
-- Dave Newbold, February 2011

library IEEE;
use IEEE.STD_LOGIC_1164.all;
use ieee.numeric_std.all;
use work.ipbus.all;

package ipbus_addr_decode is

  function ipbus_addr_sel(signal addr : in std_logic_vector(31 downto 0)) return integer;

end ipbus_addr_decode;

package body ipbus_addr_decode is
  
  function ipbus_addr_sel(signal addr : in std_logic_vector(31 downto 0)) return integer is
    variable sel : integer;
  begin
  
-- START automatically  generated VHDL the Wed Nov 28 10:33:08 2018 
    if    std_match(addr, "--------------------------------") then
      sel := 0; -- regs / base 0x00000000 / mask 0x00000000
-- END automatically generated VHD
      else
          sel := 99;
      end if;

      return sel;
      
  end ipbus_addr_sel;
                
end ipbus_addr_decode;

